CREATE TABLE KEYS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_KEY VARCHAR(36) NOT NULL,
    SECOND_KEY VARCHAR(36) NOT NULL
);

CREATE TABLE CALL_NAMES (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CALL_DATA VARCHAR(175) NOT NULL
)