CREATE TABLE KEYS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_KEY VARCHAR(35) NOT NULL,
    SECOND_KEY VARCHAR(35) NOT NULL
);

CREATE TABLE CALL_NAMES (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CALL_DATA VARCHAR(174) NOT NULL
)